version: "3.8"
services:
    db:
        image: postgis/postgis:latest
        environment:
            POSTGRES_DB: indicum
            POSTGRES_USER: indicum_user
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./db_data:/var/lib/postgresql/data
            - ./postgresql-init-scripts:/docker-entrypoint-initdb.d
            - ./csv:/var/lib/postgres-files/
